"""Functions used for outputting models for use in other programs.
Currently, only Abaqus (TM) is supported."""
import logging
import os
import time
import shutil

import numpy as np
import tabulate

from . import __version__, __website__
from . import helper

logger = logging.getLogger(__name__)


def write_abaqus_inp(part, file_name, folder_path, elem_type, dim,
                     scale, material_elem_sets,
                     custom_elem_sets=True, write_assembly=True,
                     keep_temp_files=False):
    """Write a VoxelPart object to an Abaqus (TM) input file.

    Args:
        part (VoxelPart): The VoxelPart object which is to be output.

        file_name (str): Name of the file. Must be valid according to the documentation
                         for :py:meth:`helper.is_name_valid`.
                         Also, it should not contain any file extensions.

        folder_path (str): Path to the folder where the temporary element definition file will be placed.

        elem_type (str): An uppercase string denoting the element code assigned to *all* elements.
                         It must be a valid Abaqus element code such as 'CPE4R' or 'C3D8R'.
                         No validation is performed by the function.

        dim (str): Dimensionality of the output part. Valid values are '2D' and '3D'.
                   If a 3D part is set to be output as a 2D plate, only the first row will be printed.

        scale (tuple): A tuple containing two or three floats which are used to scale the pixels or voxels
                       in the x, y, and z direction. For example, if the tuple (0.02, 0.1, 1.5) is specified,
                       each voxel will have those dimensions in the x, y, and z directions.

        material_elem_sets (tuple): A tuple of integer material codes corresponding
                                    to the materials that should be written to the output.

        custom_elem_sets (bool): If set to :py:obj:`True`, custom sets will be written to the output.
                                 Defaults to :py:obj:`True`.

        write_assembly (bool): If set to :py:obj:`True`, an instance of the part will be
                               written to the assembly without any translation or rotation.
                               Some features such as constraints require this to be :py:obj:`True`.
                               Defaults to :py:obj:`True`.

        keep_temp_files (bool): If set to :py:obj:`True`, temporary files will not be deleted.
                                Defaults to :py:obj:`False`.
    """

    logger.info("Attempting to output part '%s' to an Abaqus input file.", part.name)

    begin_time = time.perf_counter()

    # Validate file_name and add file extension.
    if not helper.is_name_valid(file_name):
        raise ValueError('Invalid file_name. Check the documentation for validity criteria.')
    file_name = file_name + '.inp'

    # Write element sets.
    (elem_set_file_path, elem_id_list, elem_set_stats) = \
        write_elem_set_def(part, material_elem_sets, folder_path, custom_elem_sets)

    # Write temporary element definition file.
    (elem_file_path, num_elems, node_id_list) = write_elem_def(part_data_shape=part.data.shape,
                                                               elem_id_list=elem_id_list,
                                                               elem_type=elem_type, dim=dim,
                                                               folder_path=folder_path)

    # Write temporary node definition file.
    (node_file_path, num_nodes) = write_node_def(part_data_shape=part.data.shape,
                                                 node_id_list=node_id_list,
                                                 scale=scale, dim=dim,
                                                 folder_path=folder_path)

    # Write the final input file.
    main_file_path = os.path.join(folder_path, file_name)
    logger.debug("Assembling temporary files to the main input file at '%s'.", main_file_path)
    with open(main_file_path, 'w', encoding='latin1') as main_file:
        # Write program details as a comment on top.
        main_file.write(('** Input file generated by VCAMS v%s' % __version__ +
                         time.strftime(' on %Y-%m-%d at %H:%M:%S %Z.\n', time.localtime()) +
                         '** VCAMS is a free and open source program available at:\n' +
                         ('** %s\n' % __website__) +
                         '** Author: Mohammadreza Khoshbin (www.mkhoshbin.com)\n\n'))

        # Write part description as heading text.
        main_file.write('*HEADING\n%s\n\n' % part.description)

        # Declare the parts portion of the input file as a comment.
        main_file.write('**\n** Parts\n**\n\n')

        # Declare this part.
        main_file.write('*PART, NAME="%s"\n\n' % part.name)

        # Write nodes.
        with open(node_file_path, 'r') as node_file:
            shutil.copyfileobj(node_file, main_file)

        # Write elements.
        with open(elem_file_path, 'r') as elem_file:
            shutil.copyfileobj(elem_file, main_file)

        # Write element sets.
        with open(elem_set_file_path, 'r') as elem_set_file:
            shutil.copyfileobj(elem_set_file, main_file)

        # Declare the end of this part.
        main_file.write('*END PART\n**\n\n')

        # Write an instance of the part to the assembly.
        if write_assembly:
            # Declare the assembly portion of the input file as a comment
            # and create an assembly.
            main_file.write('**\n** Assembly\n**\n\n')

            # Declare the assembly.
            main_file.write('*ASSEMBLY, NAME=Assembly\n\n')

            # Declare the instance.
            main_file.write('*INSTANCE, NAME="%s", PART="%s"\n' % (part.name+'-Ins', part.name))
            main_file.write('*END INSTANCE\n**\n\n')

            # TODO add constraints here.

            # Declare the end of the assembly portion of the input file.
            main_file.write('*END ASSEMBLY\n**\n\n')

    # Delete temporary file.
    if not keep_temp_files:
        logger.debug('Deleting temporary files.')
        os.remove(node_file_path)
        os.remove(elem_file_path)
        os.remove(elem_set_file_path)

    elapsed_time = time.perf_counter() - begin_time
    logger.info("Finished exporting part '%s' to the Abaqus input file at '%s'.",
                part.name, main_file_path)

    write_output_summary(part, dim, elem_type, num_nodes, num_elems, elem_set_stats, elapsed_time)


def write_elem_def(part_data_shape, elem_id_list, elem_type, dim, folder_path):
    """Write the element definition portion of an Abaqus input file to a temporary file,
    which will be concatenated with other portions to form an input file.

    Element definition consists of specifying the element code and writing its connectivity table.
    In the finite element method, the connectivity table (or matrix) determines
    which nodes belong to each element.
    The first column is always element id and its nodes are written
    in rest of the columns in a specific order based on the element geometry.

    Currently, only 2D and 3D linear elements are supported.
    To get around this, you can convert to quadratic elements after importing the model to Abaqus.

    Args:
        part_data_shape (tuple): Shape of :py:attr:`VoxelPart.~data` which can be obtained using its *shape()* method.

        elem_id_list (numpy.ndarray): A 1-D Numpy ndarray containing IDs of elements which must be output.
                                      The function makes sure that it is unique and sorted.
                                      Note that Abaqus only accepts element IDs that are positive
                                      and less than 999999999.
                                      Elements IDs must also be integers, but this is not directly checked.
                                      However, they will raise an error once they are passed as indices to numpy.

        elem_type (str): An uppercase string denoting the element code assigned to *all* elements.
                         It must be a valid Abaqus element code such as 'CPE4R' or 'C3D8R'.
                         No validation is performed by the function.

        dim (str): Dimensionality of the output part. Valid values are '2D' and '3D'.
                   If a 3D part is set to be output as a 2D plate,

        folder_path (str): Path to the folder where the temporary element definition file will be placed.

    Returns:
        tuple: The tuple *(file_path, num_elems, node_id_list)* containing
        the path to the temporary element definition file,
        the number of elements which have been written to the file,
        and a numpy ndarray containing a sorted list of node IDs that are present in the model.
    """

    logger.debug("Attempting to write element definitions to the temporary file 'elem_def.tmp'.")
    # Validate elem_id_list. Note that values are not checked.
    if len(elem_id_list) == 0:
        raise ValueError('elem_id_list is empty. At least one element must be selected for output.')
    if np.any(elem_id_list < 0):
        raise ValueError('At least on element in elem_id_list is negative' +
                         ' which will result in a non-positive ID in the input file.')
    if max(elem_id_list) >= 999999999:
        raise RuntimeError(('At least one element has an ID greater than 999999999,' +
                            ' which is not supported by Abaqus (TM).'))

    # Validate dim.
    if dim not in ['2D', '3D']:
        raise ValueError("dim can only be one of '2D' or '3D'.")

    # Make sure elem_id_list is unique and sorted.
    elem_id_list = np.unique(elem_id_list)

    # Preallocate memory for the connectivity table.
    if dim.upper() == '2D':
        elem_array_shape = part_data_shape[0:2]
        num_cols = 5
    elif dim.upper() == '3D':
        elem_array_shape = part_data_shape
        num_cols = 9
    else:
        raise RuntimeError('Unexpected value for dim. This should have been caught earlier.')
    connectivity_table = np.zeros((elem_id_list.size, num_cols), dtype=np.uint32, order='C')

    # In each direction, node array is larger by one.
    node_array_shape = tuple(i + 1 for i in elem_array_shape)

    # Find the coordinates for the elements in elem_id_list.
    elem_inds = np.unravel_index(elem_id_list, elem_array_shape, order='C')

    # Add elem_id_list as the first column.
    connectivity_table[:, 0] = elem_id_list + 1

    # For each element in elem_id_list, find its nodes.
    if dim.upper() == '2D':
        connectivity_table[:, 1] = np.ravel_multi_index(multi_index=(elem_inds[0], elem_inds[1]),
                                                        dims=node_array_shape, mode='raise', order='C') + 1
        connectivity_table[:, 2] = np.ravel_multi_index(multi_index=(elem_inds[0] + 1, elem_inds[1]),
                                                        dims=node_array_shape, mode='raise', order='C') + 1
        connectivity_table[:, 3] = np.ravel_multi_index(multi_index=(elem_inds[0] + 1, elem_inds[1] + 1),
                                                        dims=node_array_shape, mode='raise', order='C') + 1
        connectivity_table[:, 4] = np.ravel_multi_index(multi_index=(elem_inds[0], elem_inds[1] + 1),
                                                        dims=node_array_shape, mode='raise', order='C') + 1
    elif dim.upper() == '3D':
        connectivity_table[:, 1] = np.ravel_multi_index(multi_index=(elem_inds[0], elem_inds[1], elem_inds[2]),
                                                        dims=node_array_shape, mode='raise', order='C') + 1
        connectivity_table[:, 2] = np.ravel_multi_index(multi_index=(elem_inds[0] + 1, elem_inds[1], elem_inds[2]),
                                                        dims=node_array_shape, mode='raise', order='C') + 1
        connectivity_table[:, 3] = np.ravel_multi_index(multi_index=(elem_inds[0] + 1, elem_inds[1] + 1, elem_inds[2]),
                                                        dims=node_array_shape, mode='raise', order='C') + 1
        connectivity_table[:, 4] = np.ravel_multi_index(multi_index=(elem_inds[0], elem_inds[1] + 1, elem_inds[2]),
                                                        dims=node_array_shape, mode='raise', order='C') + 1
        connectivity_table[:, 5] = np.ravel_multi_index(multi_index=(elem_inds[0], elem_inds[1], elem_inds[2] + 1),
                                                        dims=node_array_shape, mode='raise', order='C') + 1
        connectivity_table[:, 6] = np.ravel_multi_index(multi_index=(elem_inds[0] + 1, elem_inds[1], elem_inds[2] + 1),
                                                        dims=node_array_shape, mode='raise', order='C') + 1
        connectivity_table[:, 7] = np.ravel_multi_index(
            multi_index=(elem_inds[0] + 1, elem_inds[1] + 1, elem_inds[2] + 1),
            dims=node_array_shape, mode='raise', order='C') + 1
        connectivity_table[:, 8] = np.ravel_multi_index(multi_index=(elem_inds[0], elem_inds[1] + 1, elem_inds[2] + 1),
                                                        dims=node_array_shape, mode='raise', order='C') + 1
    else:
        raise RuntimeError('Unexpected value for dim. This should have been caught earlier.')

    # Write the element connectivity table to a temporary text file.
    file_path = os.path.join(folder_path, 'elem_def.tmp')
    np.savetxt(fname=file_path, X=connectivity_table,
               fmt='%u', delimiter=',', comments='', encoding='latin1',
               header=('*ELEMENT, TYPE=%s' % elem_type), footer='\n')

    # Create a sorted array of unique node IDs in the connectivity matrix
    # and revert node IDs to zero-based indexing.
    node_id_list = np.unique(connectivity_table[:, 1:]) - 1
    num_elems = len(elem_id_list)

    logger.debug("Wrote %u %s elements of type '%s' to the temporary file 'elem_def.tmp'.",
                 num_elems, dim.upper(), elem_type)
    return file_path, num_elems, node_id_list


def write_node_def(part_data_shape, node_id_list, scale, dim, folder_path):
    """Write the node definition portion of an Abaqus input file to a temporary file,
    which will be concatenated with other portions to form an input file.

    Node definition consists of specifying the node ID and and writing its coordinates
    in the x, y, and z directions.

    Currently, only cartesian global coordinates are supported.

    Args:
        part_data_shape (tuple): Shape of :py:attr:`VoxelPart.~data` which can be obtained using its *shape()* method.

        node_id_list (numpy.ndarray): A 1-D Numpy ndarray containing IDs of nodes which must be output.
                                      The function makes sure that it is unique and sorted.
                                      Note that Abaqus only accepts node IDs that are positive and less than 999999999.
                                      Node IDs must also be integers, but this is not directly checked.
                                      However, they will raise an error once they are passed as indices to numpy.

        scale (tuple): A tuple containing two or three floats which are used to scale the pixels or voxels
                       in the x, y, and z direction. For example, if the tuple (0.02, 0.1, 1.5) is specified,
                       each voxel will have those dimensions in the x, y, and z directions.

        dim (str): Dimensionality of the output part. Valid values are '2D' and '3D'.
                   If a 3D part is set to be output as a 2D plate,

        folder_path (str): Path to the folder where the temporary node definition file will be placed.

    Returns:
        tuple: The tuple *(file_path, num_nodes)* containing
        the path to the temporary element definition file,
        and the number of nodes which have been written to the file.
    """

    logger.debug("Attempting to write node definitions to the temporary file 'node_def.tmp'.")
    # Validate node_id_list.
    if len(node_id_list) == 0:
        raise ValueError('node_id_list is empty. At least one node must be selected for output.')
    if np.any(node_id_list < 0):
        raise ValueError('At least on element in node_id_list is negative' +
                         ' which will result in a non-positive ID in the input file.')
    if max(node_id_list) >= 999999999:
        raise RuntimeError(('At least one node has an ID greater than 999999999,' +
                            ' which is not supported by Abaqus (TM).'))

    # Validate dim.
    if dim not in ['2D', '3D']:
        raise ValueError("dim can only be one of '2D' or '3D'.")

    # Set format string and number of columns in node_coordinates based on dim.
    if dim.upper() == '2D':
        num_cols = 3
        fmt = [('%' + str(len(str(max(node_id_list)))) + 'u'), '%13.12G', '%13.12G']
    elif dim.upper() == '3D':
        num_cols = 4
        fmt = [('%' + str(len(str(max(node_id_list)))) + 'u'), '%13.12G', '%13.12G', '%13.12G']
    else:
        raise RuntimeError('Unexpected value for dim. This should have been caught earlier.')

    # Preallocate memory for node_coordinates.
    node_table = np.zeros((node_id_list.size, num_cols), dtype=np.float64, order='C')

    # Add node_id_list as the first column of node_table.
    node_table[:, 0] = node_id_list + 1

    # Obtain Cartesian coordinates of each node by unraveling its index and multiplying it by scale.
    node_array_shape = tuple(i + 1 for i in part_data_shape)
    raw_indices = np.unravel_index(node_id_list, node_array_shape, order='C')

    # Add node coordinates to node_table.
    node_table[:, 1] = (raw_indices[0]) * scale[0]
    node_table[:, 2] = (raw_indices[1]) * scale[1]
    if dim.upper() == '3D':
        node_table[:, 3] = (raw_indices[2]) * scale[2]

    # Write node_table to a temporary text file.
    file_path = os.path.join(folder_path, 'node_def.tmp')
    np.savetxt(fname=file_path, X=node_table,
               fmt=fmt, delimiter=',', comments='', encoding='latin1',
               header='*NODE', footer='\n')

    num_nodes = len(node_id_list)

    logger.debug("Wrote %u %s nodes to the temporary file 'node_def.tmp'.", num_nodes, dim.upper())
    return file_path, num_nodes


def write_set_ids(file_obj, kind, name, ids):
    """Write an element or node set to a file according to Abaqus (TM) input file syntax.

    Args:
        file_obj (file): The file object in which the set is written.
        kind (str): The kind of set that is to be output.
                    Valid values are 'ELSET' for an element set and 'NSET' for a Node set.

        name (str): Name of the set. Must be valid according to the documentation
                    for :py:meth:`helper.is_name_valid`.

        ids (numpy.ndarray): A 1-D Numpy ndarray containing IDs of nodes or elements
                             which form the set.
                             The function makes sure that it is unique and sorted.
                             Note that Abaqus only accepts node IDs that are positive
                             and less than 999999999.
                             IDs must also be integers, but this is not directly checked.

    Returns:
        tuple: A tuple containing set name and number of IDs.
    """
    if kind.upper() not in ['ELSET', 'NSET']:
        raise ValueError("kind can only be one of 'ELSET' or 'NSET'.")

    if not helper.is_name_valid(name):
        raise ValueError('Invalid name. Check the documentation for validity criteria.')

    # Validate ids. Note that values are not checked.
    if len(ids) == 0:
        raise ValueError('ids is empty. At least one ID must be selected for output.')
    if np.any(ids < 0):
        raise ValueError('At least on element in ids is negative' +
                         ' which will result in a non-positive ID in the input file.')
    if max(ids) >= 999999999:
        raise RuntimeError(('At least one ID is greater than 999999999,' +
                            ' which is not supported by Abaqus (TM).'))
    # Make sure ids is unique and sorted.
    ids = np.unique(ids)

    # IDs start at zero (zero-based indexing).
    # Add the number 1 to all of them to account for that.
    ids = ids + 1

    # Write the set header manually.
    file_obj.write('*%s,%s="%s"\n' % (kind.upper(), kind.upper(), name))

    # If there are 9 or less IDs, they are written manually.
    # Otherwise, they are written as chunks of 9 IDs, ensuring low line length.
    # numpy.savetxt can only write a full 2D array, meaning that sometimes
    # the array needs to be broken into chunks.
    # For simplicity, the array is always broken into two chunks.
    if len(ids) <= 9:
        extra_chunk = ids
    else:
        num_extra = ids.size % 9
        if num_extra == 0:
            num_extra = 9
        main_chunk = ids[:-num_extra].reshape((-1, 9))
        extra_chunk = ids[-num_extra:]
        # Write the main chunk using numpy.
        np.savetxt(fname=file_obj, X=main_chunk,
                   fmt='%u', delimiter=',', newline=',\n', comments='', encoding='latin1',
                   header='', footer='')

    # Write the extra chunk manually.
    file_obj.write(','.join(['%u'] * len(extra_chunk)) % tuple(extra_chunk))
    file_obj.write('\n\n')

    return name, len(ids)


def write_elem_set_def(part, material_elem_sets, folder_path, custom_elem_sets=True):
    """Write the element set portion of an Abaqus input file to a temporary file.
    This function also returns which elements must be output.

    Args:
        part (VoxelPart): The VoxelPart object which is to be output.

        material_elem_sets (tuple): A tuple containing integer values of the materials
                                    that should be output. For each material *x*,
                                    a set named *'MAT-x'* is defined.

        custom_elem_sets (bool): If set to :py:obj:`True`, custom sets are defined and output.
                                 Defaults to :py:obj:`True`.

        folder_path (str): Path to the folder where the temporary node definition file will be placed.

    Returns:
        tuple: The tuple (elem_set_file_path, elem_id_list, elem_set_stats) where
               The first element is the path to the temporary element set definition file,
               the second element is a unique sorted list of all element IDs in the sets,
               and the third element is a dictionary where the keys are names
               of the element sets and the values are the number of elements in that set.
    """

    logger.debug("Attempting to write element sets to the temporary file 'elset.tmp'.")
    elem_set_stats = dict()
    elem_id_list = np.array([], order='C', dtype='uint32')
    elem_set_file_path = os.path.join(folder_path, 'elset.tmp')

    with open(elem_set_file_path, 'w', encoding='latin1') as file_obj:

        # Write custom element sets. The element IDs are unique and sorted.
        if custom_elem_sets and bool(part.elem_sets):
            for (name, elem_ids) in part.data.elem_sets.items():
                (set_name, num_ids) = write_set_ids(file_obj=file_obj, kind='ELSET',
                                                    name=name, ids=elem_ids)
                elem_id_list = np.union1d(elem_id_list, elem_ids)
                elem_set_stats[set_name] = num_ids

        # Write the the materials that should be output.
        for mat_code in material_elem_sets:
            (name, elem_ids) = part.return_material_elem_set(mat_code)
            (set_name, num_ids) = write_set_ids(file_obj=file_obj, kind='ELSET',
                                                name=name, ids=elem_ids)
            elem_id_list = np.union1d(elem_id_list, elem_ids)
            elem_set_stats[set_name] = num_ids

    logger.debug("Wrote %u element sets to the temporary file 'elset.tmp'.", len(elem_set_stats))
    return elem_set_file_path, elem_id_list, elem_set_stats


def write_output_summary(part, dim, elem_type, num_nodes, num_elems,
                         elem_set_stats, elapsed_time):
    """Write a summary of the output to the main log.

    The log file is extracted from the root logger.

    Args:
        part (VoxelPart): The VoxelPart object which is to be output.

        dim (str): Dimensionality of the output part. Valid values are '2D' and '3D'.

        elem_type (str): An uppercase string denoting the element code assigned to *all* elements.
                         It must be a valid Abaqus element code such as 'CPE4R' or 'C3D8R'.
                         No validation is performed by the function.

        num_nodes (int): Number of nodes written to the output.

        num_elems (int): Number of elements written to the output.

        elem_set_stats (dict): Dictionary returned by :py:meth:`output.write_elem_set_def`.

        elapsed_time (float): Elapsed time for the the output process in seconds.
    """

    # Prepare part summary.
    part_summary = (
        ('Part Name', part.name),
        ('Part   Dimensions', '*'.join(str(i) for i in part.data.shape)),
        ('Output Dimensions', dim.upper()),
        ('Element Type', elem_type),
        ('Number of Elements', num_elems),
        ('Number of Nodes', num_nodes),
        ('Total Output Time', time.strftime('%H:%M:%S', time.gmtime(elapsed_time)))
    )

    # Prepare set stats.
    mat_elem_sets = []
    custom_elem_sets = []
    elem_set_stats_list = sorted(elem_set_stats.items(), key=lambda x: x[1], reverse=True)
    for item in elem_set_stats_list:
        if item[0].upper().startswith('MAT-'):
            mat_elem_sets.append((item[0], item[1],
                                  '{:.2f}'.format((item[1] / num_elems) * 100),
                                  '{:.2f}'.format((item[1] / part.data.size) * 100)))
        else:
            custom_elem_sets.append((item[0], item[1], '{:.2f}'.format((item[1] / num_elems) * 100)))
    logger_stream = logger.root.handlers[0].stream
    logger_stream.writelines((
        '\nModel Details\n',
        tabulate.tabulate(part_summary, tablefmt='pretty', colalign=('left', 'left')) + '\n',
        '\nMaterial Element Sets\n',
        tabulate.tabulate(mat_elem_sets,
                          headers=('Set Name', 'Number of Elements',
                                   'Percent of All Elements', 'Percent of Model'),
                          tablefmt='pretty', colalign=('left', 'left', 'left')) + '\n',
    ))

    if len(custom_elem_sets) == 0:
        logger_stream.writelines((
            '\nCustom Element Sets\n',
            'No custom element sets were defined.\n\n'
        ))
    else:
        logger_stream.writelines((
            '\nCustom Element Sets\n',
            tabulate.tabulate(custom_elem_sets,
                              headers=('Set Name', 'Number of Elements', 'Percent of All Elements'),
                              tablefmt='pretty') + '\n',
        ))

    logger_stream.flush()
